# Generated by Django 5.2.17 on 2026-08-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('amenities', models.CharField(blank=True, help_text='Comma separated, e.g. Parking, Food Court, Recliners', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cinemas/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('screen_type', models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('dolby', 'Dolby Atmos'), ('platinum', 'Platinum'), ('screenx', 'ScreenX'), ('vip', 'VIP Lounge')], default='standard', max_length=20)),
                ('rows', models.PositiveIntegerField(default=10, help_text='Number of seat rows')),
                ('columns', models.PositiveIntegerField(default=12, help_text='Seats per row')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='cinemas.cinema')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('vip', 'VIP')], db_index=True, default='regular', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinemas.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='catalog.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinemas.screen')),
            ],
            options={
                'ordering': ['show_date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('cinema', 'name'), name='unique_screen_name_per_cinema'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('screen', 'row', 'number'), name='unique_seat_in_screen'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('screen', 'show_date', 'start_time'), name='unique_showtime_in_screen'),
        ),
    ]
